name: Deploy Laravel to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy to VM
      run: |
        sshpass -p "${{ secrets.DEPLOY_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
          cd /var/www/website-gymnation
            sudo git pull origin main
            sudo composer install --no-dev --optimize-autoloader
            sudo php artisan migrate --force
            sudo php artisan config:clear
            sudo php artisan cache:clear
            sudo php artisan route:clear
          sudo systemctl reload apache2
        EOF
